name: Lint

on:
  workflow_dispatch:
  pull_request:

jobs:
        
  css:
    name: Lint css
    runs-on: ubuntu-latest
    steps:
      - name: check out code ğŸ›
        uses: actions/checkout@v2
        
      - name: npm ci
        run: |
          npm ci
          cd web-server
          npm ci
    
      - name: Run Stylelint css
        run: npm run stylelint-css

  scss:
    name: Lint scss
    runs-on: ubuntu-latest
    steps:
      - name: check out code ğŸ›
        uses: actions/checkout@v2
        
      - name: npm ci
        run: |
          npm ci
          cd web-server
          npm ci
    
      - name: Run Stylelint scss
        run: npm run stylelint-scss
        
  js-ts:
    name: Lint js-ts
    runs-on: ubuntu-latest
    steps:
      - name: check out code ğŸ›
        uses: actions/checkout@v2
        
      - name: npm ci
        run: |
          npm ci
          cd game
          npm ci
          cd ../web-server
          npm ci
    
      - name: Run ESLint
        run: npm run eslint
        
  html:
    name: Lint html
    runs-on: ubuntu-latest
    steps:
      - name: check out code ğŸ›
        uses: actions/checkout@v2
        
      - name: npm ci
        run: |
          npm ci
          cd web-server
          npm ci
    
      - name: Run HTML-Validate
        run: npm run html-validate

  ejs:
    name: Lint ejs templates
    runs-on: ubuntu-latest
    steps:
      - name: check out code ğŸ›
        uses: actions/checkout@v2
        
      - name: npm ci
        run: |
          npm ci
          cd web-server
          npm ci
    
      - name: Run ejs-Validate
        run: npm run ejs-validate