name: Lint - Push

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'push-action/**'

jobs:
  css:
    name: Lint css
    runs-on: ubuntu-latest
    steps:
      - name: check out code ðŸ›Ž
        uses: actions/checkout@v2
        
      - name: npm ci
        run: |
          npm ci
          cd web-server
          npm ci
    
      - name: Run Stylelint css
        run: npm run stylelint-css
        
      - uses: actions/upload-artifact@v2
        with:
          name: css-linted
          path: | 
            ./**/*.css
            !node_modules/

  scss:
    name: Lint scss
    runs-on: ubuntu-latest
    steps:
      - name: check out code ðŸ›Ž
        uses: actions/checkout@v2
        
      - name: npm ci
        run: |
          npm ci
          cd web-server
          npm ci
    
      - name: Run Stylelint scss
        run: npm run stylelint-scss

      - uses: actions/upload-artifact@v2
        with:
          name: scss-linted
          path: | 
            ./**/*.scss
            !node_modules/
        
  js-ts:
    name: Lint js-ts
    runs-on: ubuntu-latest
    steps:
      - name: check out code ðŸ›Ž
        uses: actions/checkout@v2
        
      - name: npm ci
        run: |
          npm ci
          cd game
          npm ci
          cd ../web-server
          npm ci
    
      - name: Run ESLint
        run: npm run eslint
        
      - uses: actions/upload-artifact@v2
        with:
          name: js-ts-linted
          path: | 
            ./**/*.ts
            ./**/*.js
            !node_modules/
        
  html:
    name: Lint html
    runs-on: ubuntu-latest
    steps:
      - name: check out code ðŸ›Ž
        uses: actions/checkout@v2
        
      - name: npm ci
        run: |
          npm ci
          cd web-server
          npm ci
    
      - name: Run HTML-Validate
        run: npm run html-validate

  ejs:
    name: Lint ejs templates
    runs-on: ubuntu-latest
    steps:
      - name: check out code ðŸ›Ž
        uses: actions/checkout@v2
        
      - name: npm ci
        run: |
          npm ci
          cd web-server
          npm ci
    
      - name: Run ejs-Validate
        run: npm run ejs-validate
        
  push:
    name: Push changes
    runs-on: ubuntu-latest
    needs: [css, scss, js-ts, html, ejs]
    steps:
      - name: check out code ðŸ›Ž
        uses: actions/checkout@v2
        
      - uses: actions/download-artifact@v2
        with:
          name: css-linted

      - uses: actions/download-artifact@v2
        with:
          name: scss-linted
          
      - uses: actions/download-artifact@v2
        with:
          name: js-ts-linted
    
      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Auto-lint" -a
      
      - name: Pushing
        continue-on-error: true
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
          branch: main